# no_perms_message - Message if player has no permission.
# Hub - Location set for the Hub.
# Shop - Location set for the Shop.
no_perms_message: '&4You do not have permission to do that command!'
#Cannot be sold in shop message
no_sell_message: This item cannot be sold in shop
Shop:
	LavaBucket_price: $75
	WaterBucket_price: $50